version: "3"

services:

  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/nodets-prometheus-grafana



