version: "3"

networks:
  monitor-net:
    driver: bridge

services:
  nodets:
    build: ./nodets
    entrypoint: ./.docker/entrypoint.sh
    container_name: nodets
    ports:
      - 3333:3333
    volumes:
      - ./nodets:/home/node/nodets
    networks:
      - monitor-net
  prometheus2:
    container_name: prometheus2
    image: prom/prometheus:latest
    volumes: 
        - ./server/prometheus:/prometheus
    command: ["--config.file=prometheus.yml"]
    ports: 
        - 9090:9090
    networks:
        - monitor-net
  grafana2:
    image: grafana/grafana:latest
    container_name: grafana2
    volumes:
      - ./server/grafana/data:/var/lib/grafana
      - ./server/grafana/datasources:/etc/grafana/datasources
      - ./server/grafana/dashboards:/etc/grafana/dashboards
      - ./server/grafana/setup.sh:/setup.sh
    # entrypoint: /setup.sh
    environment:
        - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
        - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
        - GF_USERS_ALLOW_SIGN_UP=false
        - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel
    restart: unless-stopped
    expose:
        - 4000
    ports:
        - 4000:3000
    networks:
        - monitor-net        
